version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    # image: my_wob_app:lzw_web
    # container_name: flask_app
    ports:
      - "5050:5050"
    volumes:
      - ./:/app
    depends_on:
      - mysql
    # environment:
    #   MYSQL_HOST: mysql
    #   MYSQL_USER: root
    #   MYSQL_PASSWORD: 123456
    #   MYSQL_DB: diary_db
    restart: always
    command : sh -c "python /app/houtai.py"
    # command: >
    #   sh -c "python -m debugpy --listen 0.0.0.0:5678 --wait-for-client  /app/houtai.py"
    networks:
      - net

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: diary_db
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    command: ['--default-authentication-plugin=mysql_native_password']
    # container_name: mysql_db
    # restart: always
    ports:
     - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
    networks:
      - net

networks:
  net:
    driver: bridge
