services:
  app:
    build: .
    working_dir: /app
    ports:
      - 5050:5050   
      - 5678:5678 
    volumes:
      - ./:/app
    restart: always
    # command: sh -c "tail -f /dev/null"
    command: >
      sh -c "python -m debugpy --listen 0.0.0.0:5678 --wait-for-client  /app/houtai.py"